[package]
name = "api"
edition.workspace = true
publish.workspace = true
version.workspace = true
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
#
configs = {path = "../configs"}
db = {path = "../db"}
app-service = {path = "../service"}
middleware-fn = {path="../middleware-fn"}
# 
axum = {workspace = true, features = ["multipart"]}
#tower-http = {workspace = true}
tower-http = {workspace = true, features = ["cors","fs","compression-gzip"]}  #compression-gzip
#
futures = {workspace = true}
# 
tokio-stream = {workspace = true}
# 
serde_json = {workspace = true}
# 
headers = {workspace = true}
# 
tokio = {workspace = true}
#
anyhow = {workspace = true}
# 
reqwest = {workspace = true,  features = ["json"]}